### ISSUE TITLE
Improve the Look and Cosmetics of the Website

### ISSUE THREAD

**Issue by davischristianson** [davischristianson/Card-Creation-Website#53]
Add to this as we go along so we can separate the individual pages into issues themselves, it'll help keep track of everything. Once everything is finished we can consider closing this issue. If more pages are added later those can be separate issues instead of reopening this issue, or whatever is preferred. 
- [ ] Add/Improve Home page
- [ ] Add/Improve onto Privacy Page
- [ ] Add/Improve onto Create Account Page
